### ISSUE TITLE
cant sign in

### ISSUE THREAD

**Issue by hunter1026** [retromp3/retro#39]
trying to sign into spotify. not working on my iphone or android

**Comment by fritzlb** [comment]
how did you install the app onto your devices? did you compile it, sideloaded it, used testflight/play store/... ?

**Comment by hunter1026** [comment]
testflight and play store

**Comment by hunter1026** [comment]
it says connection error occurred

**Comment by hunter1026** [comment]
it works now that i have spotify installed

**Comment by sakofchit** [comment]
![giphy](https://github.com/retromp3/retro/assets/7917503/1c77745f-cc50-496c-8400-ee26bcc29bf0)
